version = "3.10.4"
runner.dialect = scala3

maxColumn = 110
align.preset = more
spaces.inImportCurlyBraces = true

rewrite.rules = [SortImports, RedundantParens, SortModifiers]
rewrite.redundantBraces.stringInterpolation = true
rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.removeOptionalBraces = no

fileOverride {
  "glob:**/*.sbt" {
    runner.dialect = sbt1
  }
  "glob:**/project/*.scala" {
    runner.dialect = scala213
  }
}
