blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://discord.gg/bVRQzgSbPq
    about: GitHub issues are meant for tracking enhancements and bugs, not general support. Instead, search the Wiki, Playstrategy Forum, StackOverflow, or join our Discord.
