export const perf = {
  icons: {
    ultraBullet: '{',
    bullet: 'T',
    blitz: ')',
    rapid: 'C',
    classical: '+',
    correspondence: ';',
    chess960: "'",
    kingOfTheHill: '(',
    threeCheck: '.',
    fiveCheck: '.',
    antichess: '@',
    atomic: '>',
    horde: '_',
    linesOfAction: '',
    international: 'K',
    antidraughts: 'K',
    breakthrough: 'K',
    russian: 'K',
    brazilian: 'K',
    pool: 'K',
    fromPositionDraughts: 'K',
    frisian: 'K',
    frysk: 'K',
  },
};
