name: Build assets

on:
  push:
    paths:
      - '.github/workflows/assets.yml'
      - 'public/**'
      - 'ui/**'
      - 'package.json'
      - 'yarn.lock'
  pull_request:
    paths:
      - '.github/workflows/assets.yml'
      - 'public/**'
      - 'ui/**'
      - 'package.json'
      - 'yarn.lock'
      #add back end options to ensure full build gets triggered
      - 'app/**'
      - 'conf/**'
      - 'modules/**'
      - 'project/**'
      - 'translation/source/**'
      - 'build.sbt'
      - 'lila'

jobs:
  assets:
    runs-on: ubuntu-latest
    steps:
      - name: Check if actor is an org member
        id: check_membership
        run: |
          ORG="Mind-Sports-Games"
          ACTOR="${{ github.actor }}"
          RESULT=$(curl -L -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/orgs/$ORG/members/$ACTOR" -o /dev/null -w '%{http_code}')
          if [ "$RESULT" -ne 204 ]; then
            echo "Actor $ACTOR is not a member of the organization $ORG. Exiting."
            exit 1
          fi
      - name: Run your main job
        run: echo "The actor is an organization member. Running the workflow."
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.MSO_CI_SSH_KEY }}
      - run: git submodule absorbgitdirs
      - uses: actions/checkout@v4
        with:
          repository: Mind-Sports-Games/ab
          ssh-key: ${{ secrets.id_rsa_ab }}
          ref: master
          path: ab
        continue-on-error: true
        id: ab
      - run: yarn link --cwd "$GITHUB_WORKSPACE/ab" && yarn link ab --cwd ui/round
        if: steps.ab.outcome == 'success'
      - run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
        id: yarn-cache
      - uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - uses: actions/setup-node@v4
        with:
          node-version: '14'
          cache: yarn
      - run: yarn install --network-concurrency 1
      - run: ./ui/build prod
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v2.0
        with:
          timeZone: 8
          format: 'YYYYMMDD-HHmmss'
      - name: Master -- S3 Sync Assets
        uses: jakejarvis/s3-sync-action@master
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-2'
          SOURCE_DIR: 'public'
          DEST_DIR: 'assets-${{ steps.time.outputs.time }}'
      - name: Master -- S3 Sync Assets 2
        uses: jakejarvis/s3-sync-action@master
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-2'
          SOURCE_DIR: 'public'
          DEST_DIR: 'assets'
      - name: Dev -- S3 Sync Assets
        uses: jakejarvis/s3-sync-action@master
        if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_DEV_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-2'
          SOURCE_DIR: 'public'
          DEST_DIR: 'assets-${{ steps.time.outputs.time }}'
      - name: Dev -- S3 Sync Assets 2
        uses: jakejarvis/s3-sync-action@master
        if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_DEV_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-2'
          SOURCE_DIR: 'public'
          DEST_DIR: 'assets'
      - run: mkdir assets && mv public assets/ && cp LICENSE COPYING.md README.md assets/ && git log -n 1 --pretty=oneline > assets/commit.txt
        if: (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev') && github.event_name == 'push'
      - run: cd assets && tar -cvpJf ../assets.tar.xz . && cd -
        if: (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev') && github.event_name == 'push'
        env:
          XZ_OPT: '-0'
      - uses: actions/upload-artifact@v4
        if: (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev') && github.event_name == 'push'
        with:
          name: lila-assets
          path: assets.tar.xz
