name: Run Workflow for Org Members Only

on:
  workflow_call:

jobs:
  check-org-member:
    runs-on: ubuntu-latest
    steps:
      - name: Check if actor is an org member
        id: check_membership
        run: |
          ORG="Mind-Sports-Games"
          ACTOR="${{ github.actor }}"
          RESULT=$(curl -L -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/orgs/$ORG/members/$ACTOR" -o /dev/null -w '%{http_code}')
          if [ "$RESULT" -ne 204 ]; then
            echo "Actor $ACTOR is not a member of the organization $ORG. Exiting."
            exit 1
          fi
      - name: Run your main job
        run: echo "The actor is an organization member. Running the workflow."
