on:
  workflow_call:
    inputs:
      java-version:
        type: string
        required: true
        default: '17.0.5'
      node-version:
        type: string
        required: true
        default: '20'
      ubuntu-version:
        type: string
        required: true
        default: '24.04'
      job:
        type: string
        required: true

jobs:
  deploy_assets:
    runs-on: ubuntu-${{ inputs.ubuntu-version }}
    steps:
      - name: Check if organization member
        id: check_org_member
        uses: Mind-Sports-Games/check-org-member@v1.1.0
        with:
          username: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Failed
        if: ${{ steps.check_org_member.outputs.result == 'false' }}
        run: |
          echo User Does Not Belong to Mind-Sports-Games
          exit 1
      - name: Check Passed
        run: echo The actor is an organization member
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.MSO_CI_SSH_KEY }}
      - run: git submodule absorbgitdirs
      - name: install Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - name: Install PNPM and run pnpm install
        uses: pnpm/action-setup@v4
        with:
          run_install: |
            - recursive: false
              args: [--no-frozen-lockfile, --strict-peer-dependencies]
      - run: node -v && pnpm -v && pnpm tsc -v && pnpm list
      - name: Build files
        run: ./ui/build --no-install --prod
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v2.0
        with:
          timeZone: 8
          format: 'YYYYMMDD-HHmmss'
      - name: Dev -- S3 Sync Assets
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_DEV_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-2'
          SOURCE_DIR: 'public'
          DEST_DIR: 'assets-${{ steps.time.outputs.time }}'
      - name: Dev -- S3 Sync Assets 2
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_DEV_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-2'
          SOURCE_DIR: 'public'
          DEST_DIR: 'assets'
      - run: mkdir assets && mv public assets/ && cp LICENSE COPYING.md README.md assets/ && git log -n 1 --pretty=oneline > assets/commit.txt
      - run: cd assets && tar -cvpJf ../assets.tar.xz . && cd -
        env:
          XZ_OPT: '-0'
      - uses: actions/upload-artifact@v4
        with:
          name: lila-assets
          path: assets.tar.xz

  deploy_server:
    runs-on: ubuntu-${{ inputs.ubuntu-version }}
    env:
      JAVA_OPTS: '-Xmx20g'
      SBT_OPTS: '-Dsbt.ci=true'
    steps:
      - name: Check if organization member
        id: check_org_member
        uses: Mind-Sports-Games/check-org-member@v1.1.0
        with:
          username: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Failed
        if: ${{ steps.check_org_member.outputs.result == 'false' }}
        run: |
          echo User Does Not Belong to Mind-Sports-Games
          exit 1
      - name: Check Passed
        run: echo The actor is an organization member
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.MSO_CI_SSH_KEY }}
      - name: Checkout Mind-Sports-Games/lila-maven
        uses: actions/checkout@v4
        with:
          repository: Mind-Sports-Games/lila-maven
          ssh-key: ${{ secrets.MSO_CI_SSH_KEY }}
          path: deps/lila-maven
      - uses: actions/cache@v4
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/Dependencies.scala') }}
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}
          cache: sbt
      - name: Setup sbt
        uses: sbt/setup-sbt@v1
      - run: TZ=UTC git log -1 --date=iso-strict-local --pretty='format:app.version.commit = "%h"%napp.version.date = "%ad"%napp.version.message = """%s"""%n' | tee conf/version.conf
      - run: ./lila -Depoll=true "test;stage"
      - run: cp LICENSE COPYING.md README.md target/universal/stage && git log -n 1 --pretty=oneline > target/universal/stage/commit.txt
      - run: cd target/universal/stage && tar -cvpJf ../../../lila-3.0.tar.xz . && cd -
        env:
          XZ_OPT: '-0'
      - uses: actions/upload-artifact@v4
        with:
          name: lila-server
          path: lila-3.0.tar.xz
      - name: Dev -- Copy file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PSD_MAIN_HOST }}
          username: ${{ secrets.PSD_MAIN_USERNAME }}
          key: ${{ secrets.MSO_CI_SSH_KEY }}
          source: 'lila-3.0.tar.xz'
          target: '/tmp/'
      - name: Dev -- Upgrade application
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: /opt/lila/upgrade.sh lila /tmp/lila-3.0.tar.xz
          host: ${{ secrets.PSD_MAIN_HOST }}
          username: ${{ secrets.PSD_MAIN_USERNAME }}
          privateKey: ${{ secrets.MSO_CI_SSH_KEY }}
