name: Deploy Branch to Dev

on:
  workflow_dispatch:

jobs:
  deploy_assets:
    uses: ./.github/workflows/deploy_assets_dev.yml
    with:
      job: deploy_assets
    secrets: inherit

  deploy_server:
    uses: ./.github/workflows/deploy_server_dev.yml
    with:
      job: deploy_server
    secrets: inherit
    needs: deploy_assets
    if: ${{ needs.deploy_assets.result == 'success' }}

  notify:
    runs-on: ubuntu-24.04
    env:
      WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL_DEPLOY_DEV }}
    needs: deploy_server
    if: ${{ needs.deploy_server.result == 'success' }}
    steps:
      - name: Notify
        run: |
          curl --request POST \
            --data-urlencode "content=:white_check_mark: **lila** branch <https://github.com/Mind-Sports-Games/lila/tree/${GITHUB_REF##*/}> is on <https://playstrategy.dev>" \
            $WEBHOOK_URL
