name: Deploy Branch to Dev

on:
  workflow_dispatch:

jobs:
  deploy_to_dev:
    runs-on: ubuntu-24.04
    steps:
      - name: deploy assets
        uses: ./.github/workflows/common_dev.yml
        with:
          job: deploy_assets
      - name: deploy server
        uses: ./.github/workflows/common_dev.yml
        with:
          job: deploy_server
