name: Deploy Branch to Dev

on:
  workflow_dispatch:
    inputs:
      ubuntu-version:
        required: true
        default: '24.04'
        type: string
#  push:
#    branches:
#      - dev

jobs:
  deploy_to_dev:
    runs-on: ubuntu-${{ inputs.ubuntu-version }}
    steps:
      - name: deploy assets
        uses: ./.github/workflows/common_dev.yml
        with:
          job: deploy_assets
      - name: deploy server
        uses: ./.github/workflows/common_dev.yml
        with:
          job: deploy_server
