name: Lint code

on:
  push:
    branches-ignore:
      - 'l10n_master'
  pull_request:
    paths-ignore:
      - 'translation/dest/**'

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Check if organization member
        id: check_org_member
        uses: Mind-Sports-Games/check-org-member@v1.1.0
        with:
          username: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Failed
        if: ${{ steps.check_org_member.outputs.result == 'false' }}
        run: |
          echo User Does Not Belong to Mind-Sports-Games
          exit 1
      - name: Check Passed
        run: echo The actor is an organization member
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.MSO_CI_SSH_KEY }}
      - name: Retrieve last code from Github
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: git submodule absorbgitdirs
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install PNPM and run pnpm install
        uses: pnpm/action-setup@v4
        with:
          run_install: |
            - recursive: false
              args: [--no-frozen-lockfile, --strict-peer-dependencies]
      - run: pnpm lint
      - run: pnpm check-format
