name: Lint code

on:
  push:
    branches-ignore:
      - 'l10n_master'
  pull_request:
    paths-ignore:
      - 'translation/dest/**'

jobs:
  check_org_member:
    uses: ./.github/workflows/check-org-members.yml

  lint:
    needs: check_org_member
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.MSO_CI_SSH_KEY }}
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: git submodule absorbgitdirs
      - run: echo "::set-output name=dir::$(yarn cache dir)"
        id: yarn-cache
      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: yarn
      - run: yarn install --network-concurrency 1
      - run: yarn run lint
      - run: yarn run check-format
